project_name: rudder
release:
  github:
    owner: ryantking
    name: rudder
builds:
  - binary: rudder
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - 386
    env:
    - CGO_ENABLED=0
    main: ./cmd/rudder/
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
archive:
  format: tar.gz
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary  }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
  files:
    - LICENSE
    - README.md
snapshot:
  name_template: "SNAPSHOT-{{ .Commit }}"
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version}}-checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^dev:'
    - 'README'
    - Merge pull request
    - Merge branch
brew:
  github:
    owner: ryantking
    name: homebrew-tap
  folder: Formula
  homepage: github.com/ryantking/rudder
  description: Portable Kubernetes deployment tool
  test: |
    system "${bin}/rudder --version"
