language: go
go: 1.12.x
install: true
env:
  global:
    - GOPROXY=https://goproxy.io
    - CC_TEST_REPORTER_ID=e9d5f2fb8eb605d9b5d86c797fdd0bb2372e8129fcfcd4b6d1b33edece8d54e7
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - go get github.com/axw/gocov/gocov
script:
  - make test
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  - provider: script
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
